A2 priority queue
ShishkinAndrey/PY111 pull request #3
Opened 2020-12-20 15:55 UTC by ShishkinAndrey

Шишкин Андрей Сергеевич
Тесты выполнены

2020-12-20 17:56 UTC, ShishkinAndrey commented
Commit от 17.12.20 выполнен случайно. 
Причина: создавал ветку а2 priority queue создал случайно не от master, а от ветки a1

2020-12-22 18:41 UTC, aeksei requested changes
---

Если стоит статус **Changes requested**, то нужно в данную ветку внести обязательные изменения, которые представлены ниже. Если выше представлены комментарии, то они носят рекомендательный характер.
После нужно сделать "push", тогда коммиты с изменениями сразу попадут в "pull request". 
После этого нужно будет запросить "re-request review"

2020-12-22 18:41 UTC, aeksei commented on Tasks/a2_priority_queue.py
> +    return None if len(queue_priority) == 0 else queue_priority.pop(-1)
`if len(queue_priority) == 0` не очень хорошо, лучше `if not queue_priority` если требуется проверить только наличие элементов в последовательности

2020-12-24 16:01 UTC, aeksei approved these changes
Проверено

---

Если стоит **Changes approved**, то смело можно сливать ветки. 
И после слияния удалять ветку.

Всё что указано просто комментариями, носит рекомендательный характер.
Для моментов, которые нужно исправить, я буду запрашивать изменения.

2020-12-24 16:51 UTC, merged