b0 linear search
ShishkinAndrey/PY111 pull request #7
Opened 2020-12-24 17:06 UTC by ShishkinAndrey

Шишкин Андрей Сергеевич
Тесты выполнены

2020-12-24 17:28 UTC, aeksei requested changes
---

Если стоит статус **Changes requested**, то нужно в данную ветку внести обязательные изменения, которые представлены ниже. Если выше представлены комментарии, то они носят рекомендательный характер.
После нужно сделать "push", тогда коммиты с изменениями сразу попадут в "pull request". 
После этого нужно будет запросить "re-request review"

2020-12-24 17:28 UTC, aeksei commented on Tasks/b0_linear_search.py
> +    for i in arr:
вернуть нужно индекс минимального элемента, а вы просто перебираете значения
здесь об индексах даже речи нет)))

2020-12-24 17:36 UTC, aeksei commented on Tasks/b0_linear_search.py
> +    for i in arr:
Мой косяк, не доглядел про `index` в конце))
В данном случае это я бы назвал читерством))) По сути сложность вашего алгоритма O(2n), что в итоге равно O(n)

Ограничение следующие, чтобы за один проход по последовательности получить индекс минимального элемента. Без использования встроенных функций

2020-12-24 18:07 UTC, ShishkinAndrey commented on Tasks/b0_linear_search.py
> +    for i in arr:
Согласен, что сделал читерски. Не специально , что-то не подумал

2021-01-20 15:09 UTC, aeksei approved these changes
Проверено

---

Если стоит **Changes approved**, то смело можно сливать ветки. 
И после слияния удалять ветку.

Всё что указано просто комментариями, носит рекомендательный характер.
Для моментов, которые нужно исправить, я буду запрашивать изменения.

2021-01-20 16:25 UTC, merged